<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ATMECSINLT-085" ignored="0" name="Test validate IEcom.atmecs.assesment_dbmanagement.testscripts.TestVerifyHeatClinic" tests="1" failures="1" timestamp="14 Nov 2019 14:15:37 GMT" time="101.198" errors="0">
  <testcase name="verifyHeatClinic" time="81.879" classname="com.atmecs.assesment_dbmanagement.testscripts.TestVerifyHeatClinic">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.atmecs.assesment_dbmanagement.pages.HeatClinicHomePage.validateProduct(HeatClinicHomePage.java:55)
at com.atmecs.assesment_dbmanagement.testscripts.TestVerifyHeatClinic.verifyHeatClinic(TestVerifyHeatClinic.java:78)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyHeatClinic -->
</testsuite> <!-- Test validate IEcom.atmecs.assesment_dbmanagement.testscripts.TestVerifyHeatClinic -->
